switch to pro container

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,10 +4,8 @@ orbs:
   artifactory: sandbox/artifactory@volatile
 
 jobs:
-  use-commands:
-    docker:
-      - image: circleci/openjdk:8
-      - image: docker.bintray.io/jfrog/artifactory-oss:latest
+  executor: with-rt-container
+      - image: docker.bintray.io/jfrog/artifactory-pro:latest
     steps:
       # These steps are solely for use in the test project to configure the Artifactory OSS instance used for testing.
       - checkout
@@ -31,14 +29,15 @@ workflows:
     jobs:
       - use-commands
       # cant use job level in testing until we have hosted artiactory, or custom executors
-      #- artifactory/upload:
-      #    name: Test Upload
-      #    source: test/artifact.jar
-      #    target: repo/path
-      #    build-steps:
-      #      - run: mvn install -B
-      #    pre-steps:
-      #      - setup-rt
+      - artifactory/upload:
+          name: Test Upload
+          source: test/artifact.jar
+          target: repo/path
+          build-steps:
+            - run: mvn install -B
+          pre-steps:
+            - setup-rt
+          executor: with-rt-oss-container
 
 
 commands:
@@ -48,6 +47,7 @@ commands:
       - run:
           name: Initialize Artifactory Image
           command: |
+            # wait for port availabiluty, otherwise curl errors out immediately
             dockerize -wait tcp://localhost:8081 -timeout 1m
             #wait for artifactory to finish startup stuff
             while true; do
@@ -59,7 +59,24 @@ commands:
               echo "Waiting for Artifactory to initialize"
               sleep 2
             done
+            #setup our license
+            echo '{"licenseKey":"'${RT_LICENSE_KEY}'"}' > license.json
+            curl -s -o /dev/null -w "%{http_code}" \
+              -uadmin:password -X POST -d @license.json http://localhost:8081/artifactory/api/system/licenses 
+            if [ "$HTTPCODE" -ne 200 ];then
+              echo "Unable to add license to Artifactory, failing build"
+              curl -uadmin:password -X POST -d @license.json http://localhost:8081/artifactory/api/system/licenses
+              exit 1
+            fi
+            #setup docker repo...
       - run: echo "export ARTIFACTORY_URL=http://localhost:8081/artifactory" >> $BASH_ENV
       - run: echo "export ARTIFACTORY_API_KEY=$(curl -uadmin:password -X POST http://localhost:8081/artifactory/api/security/apiKey | jq -r '.apiKey')" >> $BASH_ENV
 
+      
+
+executors:
+  with-rt-container:  
+    docker:
+      - image: circleci/node:10
+      - image: docker.bintray.io/jfrog/artifactory-pro:latest
 
